### ISSUE TITLE
No static field view_pager of type I in class - 

### ISSUE THREAD

**Issue by paulomcnally** [stephentuso/welcome-android#11]
```
java.lang.NoSuchFieldError: No static field view_pager of type I in class Lcom/stephentuso/welcome/R$id; or its superclasses (declaration of 'com.stephentuso.welcome.R$id' appears in /data/app/com.dak42.chacuatool-2/base.apk)
                                                                          at com.stephentuso.welcome.ui.WelcomeActivity.onCreate(WelcomeActivity.java:45)
                                                                          at android.app.Activity.performCreate(Activity.java:6251)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit
```

**Comment by paulomcnally** [comment]
Solved deleting activity_welcome.xml 

Base https://github.com/stephentuso/welcome-android/issues/7#issuecomment-223454687

Sorry
