### ISSUE TITLE
Preview fails because of dependency preference-v7:24.2.1 conflicting.

### ISSUE THREAD

**Issue by omerfarukyilmaz** [stephentuso/welcome-android#28]
I am not sure how I will help you to reproduce it but I have support library version 25.1.0 and welcome:1.1.0.

I initially get this warning/error from Android Studio:

![image](https://cloud.githubusercontent.com/assets/5538485/21472562/1f678ab6-cae9-11e6-8ce2-3e048f816ff6.png)

This crashed the preview with a stracktrace:

`java.lang.NoSuchFieldError: ViewBackgroundHelper
	at android.support.v7.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:46)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:63)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:441)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:240)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:195)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadClass(LayoutlibCallbackImpl.java:193)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:333)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:152)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:222)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at com.android.layoutlib.bridge.bars.CustomBar.<init>(CustomBar.java:95)
	at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:52)
	at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:46)
	at com.android.layoutlib.bridge.impl.Layout.createNavBar(Layout.java:284)
	at com.android.layoutlib.bridge.impl.Layout.<init>(Layout.java:140)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:301)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

When I remove the `compile 'com.stephentuso:welcome:1.1.0'` dependency from my build.gradle, everything is working again.

Is there any way we can bump up preference-v7 version to `25.1.0.` I feel like that might fix the issue.

My apologies if this is not this libraries problem but as removing this dependency was a direct solution to the preview crashing, I thought I should report it here.

Love your work and appreciate all the hard work btw 👍.

**Comment by stephentuso** [comment]
Thanks, yeah that sounds like the issue, I'll update that when I get a chance. For now you could probably change the version your app uses to 24.2.1

**Comment by omerfarukyilmaz** [comment]
@stephentuso Thanks! That sounds awesome.

Yep, that solution indeed does work. Interestingly it's only a problem for the Android Studio preview. The build works perfectly fine so far on my device.

Thank you again.

**Comment by omerfarukyilmaz** [comment]
In case anyone else is having a similar problem, this solution has fixed the rendering issues for me for some reason (even on support libraries 25.1.0):

http://stackoverflow.com/a/30749068/3050843

A simple copy and paste:

"I changed the res/values/styles.xml file from this:

<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
to this:

<style name="AppTheme" parent="Base.Theme.AppCompat.Light.DarkActionBar">
and that solved the problem."

**Comment by stephentuso** [comment]
The dependency versions have been updated in v1.1.1, this should be resolved
