### ISSUE TITLE
App crash at WelcomeHelper

### ISSUE THREAD

**Issue by sanurag51** [stephentuso/welcome-android#38]
Here is logcat

03-24 06:48:01.122 4030-4030/com.stephentuso.welcomeexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.stephentuso.welcomeexample, PID: 4030
                                                                              java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
                                                                                  at com.stephentuso.welcome.WelcomeHelper.$jacocoInit(WelcomeHelper.java:0)
                                                                                  at com.stephentuso.welcome.WelcomeHelper.<init>(WelcomeHelper.java:25)
                                                                                  at com.stephentuso.welcomeexample.MainActivity.onCreate(MainActivity.java:38)
                                                                                  at android.app.Activity.performCreate(Activity.java:6672)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_b0d6a23.Offline" on path: DexPathList[[zip file "/data/app/com.stephentuso.welcomeexample-1/base.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.stephentuso.welcomeexample-1/lib/arm, /system/lib, /vendor/lib]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                  at com.stephentuso.welcome.WelcomeHelper.$jacocoInit(WelcomeHelper.java:0) 
                                                                                  at com.stephentuso.welcome.WelcomeHelper.<init>(WelcomeHelper.java:25) 
                                                                                  at com.stephentuso.welcomeexample.MainActivity.onCreate(MainActivity.java:38) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6672) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 

i attached the screenshot of class and line no where it show the error.

![capture1](https://cloud.githubusercontent.com/assets/3815534/24249948/68162b1c-0f92-11e7-94c7-278b7da4dd27.PNG)

**Comment by stephentuso** [comment]
Have you modified any of the `build.gradle` files? This will happen if you remove `testCoverageEnabled = true` from the debug build type, make sure that your sample gradle file matches [the current one](https://github.com/stephentuso/welcome-android/blob/master/sample/build.gradle). Also, it doesn't look like you're using instant run, but if you are, try disabling it.

If neither of those are it, the code coverage set up might need to be cleaned up some.

**Comment by sanurag51** [comment]
no sir i didn't change anything anywhere i downloaded this project and run on android studio. 
what i want actually is to find the onClick of done button at last screen. I need to go on login screen after this welcome screen finish, but didn't understand where to do that. will you please help me, how do i do this. Thanks for response.

**Comment by stephentuso** [comment]
@sanurag51 You can run some code when the screen is finished, check out the [Results section of the readme](https://github.com/stephentuso/welcome-android#results).

**Comment by sanurag51** [comment]
thank you sir.

**Comment by stephentuso** [comment]
No problem
