### ISSUE TITLE
Failed Resolution and Class Not Found in API 22 and 23 devices

### ISSUE THREAD

**Issue by dkdilipkumar** [stephentuso/welcome-android#50]
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
                                                   at com.stephentuso.welcome.WelcomeHelper.$jacocoInit(WelcomeHelper.java:0)
                                                   at com.stephentuso.welcome.WelcomeHelper.<init>(WelcomeHelper.java:25)
                                                   at com.stephentuso.welcomeexample.MainActivity.onCreate(MainActivity.java:38)
                                                   at android.app.Activity.performCreate(Activity.java:6285)
                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                   at android.app.ActivityThread.access$900(ActivityThread.java:150)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:148)
                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_b0d6a23.Offline" on path: DexPathList[[zip file "/data/app/com.stephentuso.welcomeexample-1/base.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.stephentuso.welcomeexample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.stephentuso.welcomeexample-1/lib/arm, /vendor/lib, /system/lib]]
                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                   at com.stephentuso.welcome.WelcomeHelper.$jacocoInit(WelcomeHelper.java:0) 
                                                   at com.stephentuso.welcome.WelcomeHelper.<init>(WelcomeHelper.java:25) 
                                                   at com.stephentuso.welcomeexample.MainActivity.onCreate(MainActivity.java:38) 
                                                   at android.app.Activity.performCreate(Activity.java:6285) 
                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                   at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                   at android.os.Looper.loop(Looper.java:148) 
                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by stephentuso** [comment]
Looks like same stack trace as #38. Are you running the demo app or is this in your own application?

**Comment by stephentuso** [comment]
Closing due to inactivity
