### ISSUE TITLE
cannot be cast to welcome.WelcomeViewPagerIndicator

### ISSUE THREAD

**Issue by meshileya** [stephentuso/welcome-android#56]
` WelcomeViewPagerIndicator indicator = (WelcomeViewPagerIndicator) findViewById(R.id.wel_pager_indicator);`
I am getting at this point.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.techies.developer/com.techies.developer.welcomeexample.SampleWelcomeActivity}: java.lang.ClassCastException: com.stephentuso.welcome.WelcomeViewPagerIndicator cannot be cast to com.techies.developer.welcome.WelcomeViewPagerIndicator
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:182)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5682)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
                                                                                Caused by: java.lang.ClassCastException: com.stephentuso.welcome.WelcomeViewPagerIndicator cannot be cast to com.techies.developer.welcome.WelcomeViewPagerIndicator
                                                                                   at com.techies.developer.welcome.WelcomeActivity.onCreate(WelcomeActivity.java:110)
                                                                                   at android.app.Activity.performCreate(Activity.java:6161)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2507)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                   at android.os.Looper.loop(Looper.java:194) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5682) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by meshileya** [comment]
@ravidsrk @mehmetakiftutuncu @needsst 

Kindly help out, please

**Comment by stephentuso** [comment]
Could you give some more context? Are you just using the library normally?
I'm confused as to why `android.app.Instrumentation` is in the stack trace

The sample module has examples if you want to compare those to your code

**Comment by meshileya** [comment]
I am using the library added through gradle
